"""Bootstrap: make ``import conductor`` work for any host process."""

from __future__ import annotations

import os
import sys
from pathlib import Path

MARKER = "conductor_package_root"


def package_src_root() -> Path | None:
    """Directory that should be on PYTHONPATH (contains ``conductor/`` package)."""
    try:
        import conductor as _pkg

        p = Path(_pkg.__file__ or "").resolve().parent
        if p.name == "conductor" and p.parent.is_dir():
            return p.parent
    except Exception:  # noqa: BLE001
        pass

    for key in ("CONDUCTOR_ROOT", "CONDUCTOR_SRC", "CONDUCTOR_PACKAGE_ROOT"):
        raw = os.environ.get(key, "").strip()
        if not raw:
            continue
        root = Path(raw).expanduser().resolve()
        if (root / "conductor").is_dir() and (root / "conductor" / "__init__.py").is_file():
            return root
        if (root / "src" / "conductor").is_dir():
            return root / "src"

    home = os.environ.get("CONDUCTOR_HOME", "").strip() or os.environ.get("HERMES_HOME", "").strip()
    if home:
        marker = Path(home).expanduser() / MARKER
        if marker.is_file():
            try:
                line = marker.read_text(encoding="utf-8").strip().splitlines()[0].strip()
                root = Path(line).expanduser().resolve()
                if (root / "conductor").is_dir():
                    return root
                if (root / "src" / "conductor").is_dir():
                    return root / "src"
            except OSError:
                pass

    here = Path(__file__).resolve()
    src = here.parents[1]
    if src.name == "src" and (src / "conductor" / "__init__.py").is_file():
        return src
    return None


def ensure_conductor_importable() -> bool:
    try:
        import conductor  # noqa: F401

        return True
    except ImportError:
        pass
    root = package_src_root()
    if root is None:
        return False
    s = str(root)
    if s not in sys.path:
        sys.path.insert(0, s)
    try:
        import conductor  # noqa: F401

        return True
    except ImportError:
        return False


def write_package_root_marker(
    home: Path,
    src_root: Path | None = None,
    *,
    hermes_mode: bool = True,
) -> Path | None:
    root = src_root or package_src_root()
    if root is None:
        return None
    home = Path(home).expanduser()
    home.mkdir(parents=True, exist_ok=True)
    marker = home / MARKER
    marker.write_text(str(root.resolve()) + "\n", encoding="utf-8")
    repo = root.resolve().parent if root.name == "src" else root.resolve()
    envf = home / "conductor.env"
    lines = [
        "# Generated by `conductor setup` — source before launching your harness",
        f'export CONDUCTOR_HOME="{home}"',
        f'export CONDUCTOR_ROOT="{repo}"',
        f'export PYTHONPATH="{root.resolve()}${{PYTHONPATH:+:$PYTHONPATH}}"',
        'export CONDUCTOR_SOUL_MODE="${CONDUCTOR_SOUL_MODE:-resonate}"',
    ]
    if hermes_mode:
        lines.extend(
            [
                f'export HERMES_HOME="{home}"',
                'export CONDUCTOR_HOST="${CONDUCTOR_HOST:-hermes}"',
                'export CONDUCTOR_USE_HARNESS_AUTH="${CONDUCTOR_USE_HARNESS_AUTH:-1}"',
                f'export CONDUCTOR_HOST_SOUL="${{CONDUCTOR_HOST_SOUL:-{home}/SOUL.md}}"',
                f'export CONDUCTOR_PARTNER_SOUL="${{CONDUCTOR_PARTNER_SOUL:-{home}/CONDUCTOR_PARTNER_SOUL.md}}"',
                "# Prefer: pip install -e the-conductor into the Hermes venv (conductor hermes-ready --install-pip)",
            ]
        )
    else:
        lines.append("# Generic harness — set CONDUCTOR_HOST if your host has a known spawn contract")
    envf.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return marker


def _home_has_conductor_plugin(home: Path) -> bool:
    return (home / "plugins" / "conductor" / "plugin.yaml").is_file()


def shared_home_default() -> Path:
    """Default CONDUCTOR_HOME for module installs.

    Prefer a home that already has the Hermes Conductor plugin so
    ``conductor hermes-ready`` does not report NOT READY against an empty
    ``~/.conductor`` while ``~/.hermes/plugins/conductor`` is installed.
    """
    raw = (
        os.environ.get("CONDUCTOR_HOME", "").strip()
        or os.environ.get("HERMES_HOME", "").strip()  # share when host is Hermes
    )
    if raw:
        return Path(raw).expanduser().resolve()
    preferred = Path.home() / ".conductor"
    hermes = Path.home() / ".hermes"
    legacy_ilo = Path.home() / ".ilo"
    # Hermes install already wired → share that home
    if hermes.is_dir() and _home_has_conductor_plugin(hermes):
        return hermes.resolve()
    # Conductor home with plugin
    if preferred.is_dir() and _home_has_conductor_plugin(preferred):
        return preferred.resolve()
    # Existing Hermes users (no plugin yet): still share ~/.hermes for setup
    if hermes.is_dir() and not preferred.is_dir():
        return hermes.resolve()
    if preferred.is_dir():
        # Incomplete ~/.conductor without plugin — if Hermes exists, prefer it
        # so setup/ready target the real agent home.
        if hermes.is_dir():
            return hermes.resolve()
        return preferred.resolve()
    if hermes.is_dir():
        return hermes.resolve()
    if legacy_ilo.is_dir():
        return legacy_ilo.resolve()
    return preferred.resolve()
